config/routes.rb
Rails.application.routes.draw do
  resources :themes
  resources :studios
  resources :releases
  resources :languages
  resources :genres
  resources :crews
  resources :countries
  resources :actors
  resources :movies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/actor.rb
class Actor < ApplicationRecord
  belongs_to :movie
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :movie
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :movie
end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :movie
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :movie
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
end

app/models/release.rb
class Release < ApplicationRecord
  belongs_to :movie
end

app/models/studio.rb
class Studio < ApplicationRecord
  belongs_to :movie
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :movie
end

app/controllers/actors_controller.rb
# frozen_string_literal: true

class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  def index
    @actors = Actor.all.limit(300)
  end

  # GET /actors/1
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  def create
    @actor = Actor.new(actor_params)

    if @actor.save
      redirect_to(@actor, notice: "Actor was successfully created.")
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  # PATCH/PUT /actors/1
  def update
    if @actor.update(actor_params)
      redirect_to(@actor, notice: "Actor was successfully updated.", status: :see_other)
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  # DELETE /actors/1
  def destroy
    @actor.destroy!
    redirect_to(actors_url, notice: "Actor was successfully destroyed.", status: :see_other)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_actor
    @actor = Actor.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def actor_params
    params.require(:actor).permit(:movie_id, :name)
  end
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: %i[ show edit update destroy ]

  # GET /crews
  def index
    @crews = Crew.all
  end

  # GET /crews/1
  def show
  end

  # GET /crews/new
  def new
    @crew = Crew.new
  end

  # GET /crews/1/edit
  def edit
  end

  # POST /crews
  def create
    @crew = Crew.new(crew_params)

    if @crew.save
      redirect_to @crew, notice: "Crew was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /crews/1
  def update
    if @crew.update(crew_params)
      redirect_to @crew, notice: "Crew was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /crews/1
  def destroy
    @crew.destroy!
    redirect_to crews_url, notice: "Crew was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crew_params
      params.require(:crew).permit(:movie_id, :role, :name)
    end
end

app/controllers/genres_controller.rb
# frozen_string_literal: true

class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  def index
    @genres = Genre.all.limit(300)
  end

  # GET /genres/1
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  def create
    @genre = Genre.new(genre_params)

    if @genre.save
      redirect_to(@genre, notice: "Genre was successfully created.")
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  # PATCH/PUT /genres/1
  def update
    if @genre.update(genre_params)
      redirect_to(@genre, notice: "Genre was successfully updated.", status: :see_other)
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  # DELETE /genres/1
  def destroy
    @genre.destroy!
    redirect_to(genres_url, notice: "Genre was successfully destroyed.", status: :see_other)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_genre
    @genre = Genre.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def genre_params
    params.require(:genre).permit(:movie_id, :name)
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/actors/_actor.html.erb
<div id="<%= dom_id actor %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Movie:</strong>
    <%= actor.movie_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= actor.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this actor", actor, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this actor", edit_actor_path(actor), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/actors/_form.html.erb
<%= form_with(model: actor, class: "contents") do |form| %>
  <% if actor.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
        <% actor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :movie_id %>
    <%= form.text_field :movie_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing actor</h1>

  <%= render "form", actor: @actor %>

  <%= link_to "Show this actor", @actor, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to actors", actors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/actors/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Actors</h1>
    <%= link_to "New actor", new_actor_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="actors" class="min-w-full">
    <%= render @actors %>
  </div>
</div>

app/views/actors/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New actor</h1>

  <%= render "form", actor: @actor %>

  <%= link_to "Back to actors", actors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/actors/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @actor %>

    <%= link_to "Edit this actor", edit_actor_path(@actor), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this actor", actor_path(@actor), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to actors", actors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/crews/_crew.html.erb
<div id="<%= dom_id crew %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Movie:</strong>
    <%= crew.movie_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Role:</strong>
    <%= crew.role %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= crew.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this crew", crew, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this crew", edit_crew_path(crew), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/crews/_form.html.erb
<%= form_with(model: crew, class: "contents") do |form| %>
  <% if crew.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
        <% crew.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :movie_id %>
    <%= form.text_field :movie_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :role %>
    <%= form.text_field :role, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/crews/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing crew</h1>

  <%= render "form", crew: @crew %>

  <%= link_to "Show this crew", @crew, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to crews", crews_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/crews/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Crews</h1>
    <%= link_to "New crew", new_crew_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="crews" class="min-w-full">
    <%= render @crews %>
  </div>
</div>

app/views/crews/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New crew</h1>

  <%= render "form", crew: @crew %>

  <%= link_to "Back to crews", crews_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/crews/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @crew %>

    <%= link_to "Edit this crew", edit_crew_path(@crew), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this crew", crew_path(@crew), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to crews", crews_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/genres/_form.html.erb
<%= form_with(model: genre, class: "contents") do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :movie_id %>
    <%= form.text_field :movie_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<div id="<%= dom_id genre %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Movie:</strong>
    <%= genre.movie_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= genre.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this genre", genre, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this genre", edit_genre_path(genre), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/genres/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing genre</h1>

  <%= render "form", genre: @genre %>

  <%= link_to "Show this genre", @genre, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to genres", genres_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/genres/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Genres</h1>
    <%= link_to "New genre", new_genre_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="genres" class="min-w-full">
    <%= render @genres %>
  </div>
</div>

app/views/genres/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New genre</h1>

  <%= render "form", genre: @genre %>

  <%= link_to "Back to genres", genres_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/genres/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @genre %>

    <%= link_to "Edit this genre", edit_genre_path(@genre), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this genre", genre_path(@genre), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to genres", genres_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>