config/routes.rb
Rails.application.routes.draw do
  resources :themes
  resources :studios
  resources :releases
  resources :languages
  resources :genres
  resources :crews
  resources :countries
  resources :actors
  resources :movies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/actor.rb
class Actor < ApplicationRecord
  belongs_to :movie
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :movie
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :movie
end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :movie
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :movie
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
end

app/models/release.rb
class Release < ApplicationRecord
  belongs_to :movie
end

app/models/studio.rb
class Studio < ApplicationRecord
  belongs_to :movie
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :movie
end

app/controllers/actors_controller.rb
# frozen_string_literal: true

class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  def index
    @actors = Actor.all.limit(300)
  end

  # GET /actors/1
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  def create
    @actor = Actor.new(actor_params)

    if @actor.save
      redirect_to(@actor, notice: "Actor was successfully created.")
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  # PATCH/PUT /actors/1
  def update
    if @actor.update(actor_params)
      redirect_to(@actor, notice: "Actor was successfully updated.", status: :see_other)
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  # DELETE /actors/1
  def destroy
    @actor.destroy!
    redirect_to(actors_url, notice: "Actor was successfully destroyed.", status: :see_other)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_actor
    @actor = Actor.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def actor_params
    params.require(:actor).permit(:movie_id, :name)
  end
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: %i[ show edit update destroy ]

  # GET /crews
  def index
    @crews = Crew.all
  end

  # GET /crews/1
  def show
  end

  # GET /crews/new
  def new
    @crew = Crew.new
  end

  # GET /crews/1/edit
  def edit
  end

  # POST /crews
  def create
    @crew = Crew.new(crew_params)

    if @crew.save
      redirect_to @crew, notice: "Crew was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /crews/1
  def update
    if @crew.update(crew_params)
      redirect_to @crew, notice: "Crew was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /crews/1
  def destroy
    @crew.destroy!
    redirect_to crews_url, notice: "Crew was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crew_params
      params.require(:crew).permit(:movie_id, :role, :name)
    end
end

app/controllers/studios_controller.rb
# frozen_string_literal: true

class StudiosController < ApplicationController
  before_action :set_studio, only: [:show, :edit, :update, :destroy]

  # GET /studios
  def index
    @studios = Studio.all.limit(300)
  end

  # GET /studios/1
  def show
  end

  # GET /studios/new
  def new
    @studio = Studio.new
  end

  # GET /studios/1/edit
  def edit
  end

  # POST /studios
  def create
    @studio = Studio.new(studio_params)

    if @studio.save
      redirect_to(@studio, notice: "Studio was successfully created.")
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  # PATCH/PUT /studios/1
  def update
    if @studio.update(studio_params)
      redirect_to(@studio, notice: "Studio was successfully updated.", status: :see_other)
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  # DELETE /studios/1
  def destroy
    @studio.destroy!
    redirect_to(studios_url, notice: "Studio was successfully destroyed.", status: :see_other)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_studio
    @studio = Studio.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def studio_params
    params.require(:studio).permit(:movie_id, :name)
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/studios/_form.html.erb
<%= form_with(model: studio, class: "contents") do |form| %>
  <% if studio.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(studio.errors.count, "error") %> prohibited this studio from being saved:</h2>

      <ul>
        <% studio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :movie_id %>
    <%= form.text_field :movie_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/studios/_studio.html.erb
<div id="<%= dom_id studio %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Movie:</strong>
    <%= studio.movie_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= studio.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this studio", studio, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this studio", edit_studio_path(studio), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/studios/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing studio</h1>

  <%= render "form", studio: @studio %>

  <%= link_to "Show this studio", @studio, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to studios", studios_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/studios/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Studios</h1>
    <%= link_to "New studio", new_studio_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="studios" class="min-w-full">
    <%= render @studios %>
  </div>
</div>

app/views/studios/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New studio</h1>

  <%= render "form", studio: @studio %>

  <%= link_to "Back to studios", studios_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/studios/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @studio %>

    <%= link_to "Edit this studio", edit_studio_path(@studio), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this studio", studio_path(@studio), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to studios", studios_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>